# Secret string
secret: "DHJKGFksdjfghjsldFHgsyiwur89ug783rgdkhs"

# MYSQL / Root password
mysql_root: ""

# MYSQL / Like root
mysql_rootuser: ""
mysql_rootpass: ""

# Domain for subdomains new sites
host_domain: "host.ru"

# Socket
socket_port: 9999
socket_timeout: 60

# Seconds ping
timer: 1